### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by Leon-Africa** [PlagueHO/Workshop-AKS#1]
Hi there,

Thanks for the great tutorial.

What are the considerations around security? Helm - Tiller - Ingress

Would really appreciate your advise in this respect - especially when considering production use in Azure.

**Comment by Leon-Africa** [comment]
Anyone wondering about the same thing - have a look at: https://docs.microsoft.com/en-us/azure/aks/kubernetes-helm

**Comment by PlagueHO** [comment]
Hi @Leon-Africa - thank you for sharing this link! Sorry I didn't respond earlier! And I'm really glad this was helpful. 

Hopefully Helm 3 (see https://helm.sh/blog/helm-3-preview-pt2/) will also start to improve some of the security posture in running Helm as the Tiller is being completely removed.
